# Generated by Django 5.1.2 on 2024-10-11 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplaEscolha',
            fields=[
                ('questao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sistema.questao')),
            ],
            bases=('sistema.questao',),
        ),
        migrations.CreateModel(
            name='VerdadeiroOuFalso',
            fields=[
                ('questao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sistema.questao')),
            ],
            bases=('sistema.questao',),
        ),
    ]
