# Generated by Django 5.1.2 on 2024-10-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_assunto_questao_assunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='assunto',
        ),
    ]
