# Generated by Django 5.1.2 on 2024-10-11 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_remove_questao_assunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='assunto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.assunto'),
        ),
    ]
