# Generated by Django 5.1.2 on 2024-10-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_questao_assunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='solucao',
            field=models.CharField(default='Solucao', max_length=1000),
            preserve_default=False,
        ),
    ]
