# Generated by Django 5.1.2 on 2024-10-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_questao_solucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='solucao',
            field=models.TextField(max_length=1000),
        ),
    ]
