# Generated by Django 5.1.2 on 2024-10-11 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_alter_questao_solucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='sistema.questao'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='assunto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes', to='sistema.assunto'),
        ),
    ]
